BEGIN;
CREATE TABLE `protracker_alert` (`AlertID` integer NOT NULL PRIMARY KEY, `TakenAt` datetime NOT NULL);
CREATE TABLE `protracker_alertreplica` (`ReplicaID` integer NOT NULL PRIMARY KEY, `ReplicaNumber` integer NOT NULL, `ChannelID` integer NOT NULL, `ChannelProbability` double precision NOT NULL, `AlertID_id` integer NOT NULL);
CREATE TABLE `protracker_astroobject` (`AstroObjectID` integer NOT NULL PRIMARY KEY, `Catalog` varchar(500) NOT NULL, `IDinCatalog` integer NOT NULL, `IsPointSource` bool NOT NULL);
CREATE TABLE `protracker_attribute` (`AttrName` varchar(100) NOT NULL PRIMARY KEY, `IsScaled` bool NOT NULL, `DataType` varchar(500) NOT NULL);
CREATE TABLE `protracker_attributevalue` (`AttributeValueID` integer NOT NULL PRIMARY KEY, `ContainerID` integer NOT NULL, `ContainerType` varchar(1) NOT NULL, `ComputedAt` datetime NOT NULL, `Value` varchar(500) NOT NULL, `Annotation` varchar(500) NOT NULL, `Confidence` double precision NOT NULL, `AttrName_id` varchar(100) NOT NULL);
CREATE TABLE `protracker_derivedattribute` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `HashName` varchar(40) NOT NULL, `FunctionName` varchar(50) NOT NULL, `FileName` varchar(50) NOT NULL, `PackageName` varchar(50) NOT NULL, `AstronomerName` varchar(50) NOT NULL, `AttrName_id` varchar(100) NOT NULL);
CREATE TABLE `protracker_image` (`ImageID` integer NOT NULL PRIMARY KEY, `TakenAt` datetime NOT NULL, `TeloscopeName` varchar(100) NOT NULL, `FilterPassband` varchar(500) NOT NULL);
CREATE TABLE `protracker_locus` (`LocusID` integer NOT NULL PRIMARY KEY, `Coordinate` varchar(500) NOT NULL, `Uncertainty` integer NOT NULL);
CREATE TABLE `protracker_locusaggregatedalert` (`LAAID` integer NOT NULL PRIMARY KEY, `LocusID_id` integer NOT NULL);
CREATE TABLE `protracker_replicaassociatedwith` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `AssociationProbability` double precision NOT NULL, `AstroObjectID_id` integer NOT NULL, `ReplicaID_id` integer NOT NULL);
CREATE TABLE `protracker_source` (`SourceID` integer NOT NULL PRIMARY KEY, `Coordinate` varchar(500) NOT NULL, `Brightness` double precision NOT NULL, `DeltaBrightness` double precision NOT NULL, `ThumbnailURL` varchar(200) NOT NULL, `ImageID_id` integer NOT NULL);
ALTER TABLE `protracker_attributevalue` ADD CONSTRAINT `protracker_attributevalue_AttrName_id_40b1eefc95853929_uniq` UNIQUE (`AttrName_id`, `ContainerID`, `ContainerType`, `ComputedAt`);
ALTER TABLE `protracker_astroobject` ADD COLUMN `LocusID_id` integer NOT NULL;
ALTER TABLE `protracker_astroobject` ALTER COLUMN `LocusID_id` DROP DEFAULT;
ALTER TABLE `protracker_alertreplica` ADD COLUMN `LocusID_id` integer NOT NULL;
ALTER TABLE `protracker_alertreplica` ALTER COLUMN `LocusID_id` DROP DEFAULT;
ALTER TABLE `protracker_alert` ADD COLUMN `LAAID_id` integer NOT NULL;
ALTER TABLE `protracker_alert` ALTER COLUMN `LAAID_id` DROP DEFAULT;
ALTER TABLE `protracker_alert` ADD COLUMN `LocusID_id` integer NOT NULL;
ALTER TABLE `protracker_alert` ALTER COLUMN `LocusID_id` DROP DEFAULT;
ALTER TABLE `protracker_alert` ADD COLUMN `SourceID_id` integer NOT NULL;
ALTER TABLE `protracker_alert` ALTER COLUMN `SourceID_id` DROP DEFAULT;
CREATE INDEX protracker_alertreplica_fb85bbed ON `protracker_alertreplica` (`AlertID_id`);
ALTER TABLE `protracker_alertreplica` ADD CONSTRAINT `protrack_AlertID_id_6aac1d3460e6804d_fk_protracker_alert_AlertID` FOREIGN KEY (`AlertID_id`) REFERENCES `protracker_alert` (`AlertID`);
CREATE INDEX protracker_attributevalue_abdad757 ON `protracker_attributevalue` (`AttrName_id`);
ALTER TABLE `protracker_attributevalue` ADD CONSTRAINT `pr_AttrName_id_439aadca74aaac63_fk_protracker_attribute_AttrName` FOREIGN KEY (`AttrName_id`) REFERENCES `protracker_attribute` (`AttrName`);
CREATE INDEX protracker_derivedattribute_abdad757 ON `protracker_derivedattribute` (`AttrName_id`);
ALTER TABLE `protracker_derivedattribute` ADD CONSTRAINT `pr_AttrName_id_497adb3e598a9cdd_fk_protracker_attribute_AttrName` FOREIGN KEY (`AttrName_id`) REFERENCES `protracker_attribute` (`AttrName`);
CREATE INDEX protracker_locusaggregatedalert_81cd4d51 ON `protracker_locusaggregatedalert` (`LocusID_id`);
ALTER TABLE `protracker_locusaggregatedalert` ADD CONSTRAINT `protrack_LocusID_id_2a05cd489cd0a1fc_fk_protracker_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `protracker_locus` (`LocusID`);
CREATE INDEX protracker_replicaassociatedwith_5585987a ON `protracker_replicaassociatedwith` (`AstroObjectID_id`);
ALTER TABLE `protracker_replicaassociatedwith` ADD CONSTRAINT `f1be6bc95645a8e4f7f63cf6805ce7c2` FOREIGN KEY (`AstroObjectID_id`) REFERENCES `protracker_astroobject` (`AstroObjectID`);
CREATE INDEX protracker_replicaassociatedwith_2938439f ON `protracker_replicaassociatedwith` (`ReplicaID_id`);
ALTER TABLE `protracker_replicaassociatedwith` ADD CONSTRAINT `D937b96dbb54639eb864bd7e1ba1ef9b` FOREIGN KEY (`ReplicaID_id`) REFERENCES `protracker_alertreplica` (`ReplicaID`);
CREATE INDEX protracker_source_f73aa132 ON `protracker_source` (`ImageID_id`);
ALTER TABLE `protracker_source` ADD CONSTRAINT `protrack_ImageID_id_4604d1d58c2d1cc1_fk_protracker_image_ImageID` FOREIGN KEY (`ImageID_id`) REFERENCES `protracker_image` (`ImageID`);
CREATE INDEX protracker_astroobject_81cd4d51 ON `protracker_astroobject` (`LocusID_id`);
ALTER TABLE `protracker_astroobject` ADD CONSTRAINT `protrack_LocusID_id_1e30a7a6576d3986_fk_protracker_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `protracker_locus` (`LocusID`);
CREATE INDEX protracker_alertreplica_81cd4d51 ON `protracker_alertreplica` (`LocusID_id`);
ALTER TABLE `protracker_alertreplica` ADD CONSTRAINT `protrack_LocusID_id_6e4970d8ff909e06_fk_protracker_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `protracker_locus` (`LocusID`);
CREATE INDEX protracker_alert_25f9967f ON `protracker_alert` (`LAAID_id`);
ALTER TABLE `protracker_alert` ADD CONSTRAINT `D2e5b38c261db8f5651fb26348f7ae7a` FOREIGN KEY (`LAAID_id`) REFERENCES `protracker_locusaggregatedalert` (`LAAID`);
CREATE INDEX protracker_alert_81cd4d51 ON `protracker_alert` (`LocusID_id`);
ALTER TABLE `protracker_alert` ADD CONSTRAINT `protrack_LocusID_id_6684d5a04034bad4_fk_protracker_locus_LocusID` FOREIGN KEY (`LocusID_id`) REFERENCES `protracker_locus` (`LocusID`);
CREATE INDEX protracker_alert_51310f77 ON `protracker_alert` (`SourceID_id`);
ALTER TABLE `protracker_alert` ADD CONSTRAINT `protr_SourceID_id_3e69d9cf31c5a32e_fk_protracker_source_SourceID` FOREIGN KEY (`SourceID_id`) REFERENCES `protracker_source` (`SourceID`);

COMMIT;
